name: Say hello

# siempre que se ejecute un push en la rama main, se ejecutará el job hello_world, 
# que imprimirá un mensaje y la fecha actual en la consola de GitHub Actions.
on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l